source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PushForParse' do
    platform :ios, '9.0'
	pod 'Alamofire', '~> 3.0'
	pod 'Mercury'
    #pod 'DGElasticPullToRefresh'
end

target 'PushForParseWatchApp Extension' do
	platform :watchos, '2.0'
	pod 'Alamofire', '~> 3.0'
end

