source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '8.0'
use_frameworks!

target 'PushForParse' do
	pod 'Alamofire', '~> 3.0'
	pod 'Mercury'
end

target 'PushForParseWatchApp Extension' do
	platform :watchos, '2.0'
	pod 'Alamofire', '~> 3.0'
end

